### ISSUE TITLE
group icon

### ISSUE THREAD

**Issue by jsta** [hacky-hour/resources#3]
I was messing around with some icon ideas for the group. [Here](https://i.imgur.com/ngSh0eg.png) is what I came up with:

![](https://i.imgur.com/ngSh0eg.png)

Would love to see other peoples ideas.

**Comment by straussed** [comment]
I like it!

**Comment by straussed** [comment]
I made this our icon for now. We can always change it later if we want.

**Comment by jsta** [comment]
Another idea I had was to replace the filled spartan S with something like:

![](https://i.imgur.com/JZkH5OL.png)

**Comment by straussed** [comment]
that's pretty cool too...Anyone else have thoughts?
